### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by hndang** [google-developer-training/android-basics-kotlin-unscramble-app#58] opened 2021-05-13 05:05 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
step 7

**Describe the problem**
In this code:

```kotlin
while (tempWord.toString().equals(currentWord, false)) {
       tempWord.shuffle()
 }
```

tempWord.toString() will give the Char array representation not the String itself and expression is always False.
It should be changed to:
`String(tempWord)`

**Steps to reproduce?**
N/A

**Versions**
_Android Studio version:_ NA
_API version of the emulator:_ NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by roger2hk** [comment] 2021-05-13 10:36
Duplicate of #53

**Comment by jtavva** [comment] 2021-06-11 17:14
@roger2hk 
Same as #42 
Please refer to the above issue for solution.

**Closed by jtavva** 2021-06-11 17:14 UTC
