### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by ogak** [google-developer-training/android-basics-kotlin-unscramble-app#39] opened 2021-03-26 05:49 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Step 7 Populate ViewModel

**Describe the problem**
The app is crash when run the app
based on crash log  the issue is on this code 
```
if (wordsList.contains(currentWord)) {
    getNextWord()
}
```
_Note: when removing the code above the app can run_

**Steps to reproduce?**
1. Follow course "Store data in ViewModel" instruction until Step 7 "Populate ViewModel"
2. After that build & run the app
3. App is crash, see attachment for more details

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_  -

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/34905946/112587777-c9ca8800-8e30-11eb-8c8e-57c32c97e0f7.png)

**Comment by jtavva** [comment] 2021-04-20 17:51
@ogak 
Thank you for reaching out to us.
Could you make sure you have the `init{}` block above `getNextWord()`, like shown below.
![image](https://user-images.githubusercontent.com/24260141/115441462-bc9d8080-a1c5-11eb-8b09-e41a94a46fc8.png)

Alternatively please cross check your code with the solution code:
https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/blob/main/app/src/main/java/com/example/android/unscramble/ui/game/GameViewModel.kt

If you still face issues, please zip your code and send it for further assistance.

**Comment by seuygr** [comment] 2021-05-18 21:31
For future folks who may see this issue, the problem is probably you define `init` at the very top of the `GameViewModel` class, like this:
```
class GameViewModel : ViewModel() {
    init {
        Log.d("GameFragment", "GameViewModel created!")
        getNextWord()
    }
    ...
}
```
Instead, you need to define it after `wordsList` is initialized.

**Comment by jtavva** [comment] 2021-06-11 17:00
@ogak 
It's been more than 2 months since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.

**Closed by jtavva** 2021-06-11 17:00 UTC
Labels: question
