### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by negativefix** [google-developer-training/android-basics-kotlin-unscramble-app#86] opened 2021-06-22 15:25 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
"Get next word" section 6th step.

**Describe the problem**
tempWord.toString().equals(currentWord, false) always returns "false" therefore the word never gets shuffled. 

**Versions**
_Android Studio version:_  4.2.1
_API version of the emulator:_  30

**Additional information**
Replacing toString() with joinToString("") fixes the issues.

_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/1294467/122952566-c0e14800-d386-11eb-8807-ae1c6a2b4b98.png)

**Comment by PiyushSonawane1302** [comment] 2021-06-24 16:08
you need to add 
```kotlin
 tempWord.shuffle()
```
below the 
```kotlin
val tempWord = currentWord.toCharArray()
```
As you didn't shuffled the words
In while loop words are shuffled only if they are same 

```kotlin
 private fun getNextWord() {
        currentWord = allWordsList.random()
        val tempWord = currentWord.toCharArray()
        tempWord.shuffle()

        while (tempWord.toString().equals(currentWord, false)) {
            tempWord.shuffle()
        }
        if (wordsList.contains(currentWord)) {
            getNextWord()
        } else {
            _currentScrambledWord = String(tempWord)
            ++_currentWordCount
            wordsList.add(currentWord)
        }
    }
```

**Comment by thekuom** [comment] 2021-07-06 14:34
`.toString()` is wrong. `tempWord` needs to be cast differently. The line should be
```kotlin
while (String(tempWord).equals(currentWord, false)) {
```

Here is a Kotlin Playground demonstrating why `.toCharArray().toString()` doesn't work: https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS41LjIwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS4gXG4gKiBwbGF5LmtvdGxpbmxhbmcub3JnIFxuICovXG5cbmZ1biBtYWluKCkge1xuICAgIHZhbCB0ZXN0ID0gXCJ0cnVja1wiXG4gICAgdmFsIHRlc3QyID0gdGVzdC50b0NoYXJBcnJheSgpXG5cbiAgICBwcmludGxuKFwidGVzdDIudG9TdHJpbmcoKTogJHt0ZXN0Mi50b1N0cmluZygpfVwiKVxuICAgIHByaW50bG4oXCJTdHJpbmcodGVzdDIpOiAke1N0cmluZyh0ZXN0Mil9XCIpXG59In0=

![image](https://user-images.githubusercontent.com/15683724/124618394-5d065700-de3d-11eb-8da6-9f82458ad5d3.png)

**Comment by thekuom** [comment] 2021-07-06 15:30
Duplicate of https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/issues/83

**Comment by android-dev-lxl** [comment] 2023-01-17 23:48
Thank you for reporting, this issue is fixed.

**Closed by android-dev-lxl** 2023-01-17 23:48 UTC
