### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by sudaristvan** [google-developer-training/android-basics-kotlin-unscramble-app#19] opened 2021-02-01 19:15 UTC
**url of the lession
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**
Problem #1 in:
7. Populate ViewModel

Problem #2 in:
11. Verify the ViewModel preserves data

**Describe problem #1
The explanations are perfect, the challange is fair, but after the 7. step the app does not run with the in-lession solution, nor with the solution code.
I could find that problem by Debug:
the problem lies in getNextWord() method in GameViewModel.kt.
After I initialized wordList as well, the app did not crush anymore.
I added this line right after currentWord (I did not altered the lateinit declarations):
```
fun getNextWord(){
        currentWord = allWordsList.random()
        wordsList = mutableListOf()
```
since in the Debug report there was a complaint that getNextWord() is a null object or something.
Here is the relevant part of the report:

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.android.unscramble, PID: 8580
>  java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
>         at com.example.android.unscramble.ui.game.GameViewModel.getNextWord(GameViewModel.kt:44)
>         at com.example.android.unscramble.ui.game.GameViewModel.<init>(GameViewModel.kt:11)

**Describe problem #2
The app runs almost as expected, only it does not update the word count view and score view, unless I rotate the device thus restart the view.
Therefore I added in GameFragment.kt to the updateNextWordOnScreen() method two extra lines:

```
 binding.score.text = getString(R.string.score, viewModel.score)
        binding.wordCount.text = getString(
            R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS)
```

in order to update not just the word but the score and word count as well. 

NOTE: before I wrote you, I double checked my code to rule out my faults, but it is still possible that the reported problems were due to my mistakes. In that case I am sorry for taking your time. Even so, you can consider this as an overall feedback on your training, since you made me able to spot the missing parts. Thank you for this training!

**Versions**
_Android Studio version: 4.1.2
_API version of the emulator: Pixel 4 XL API 29

**Comment by sudaristvan** [comment] 2021-02-01 19:31
After taking the next lession (Use LiveData with ViewModel) I see now my 2nd problem is not a problem.
After reading other comments on this lession my 1st problem seems to be solved in a proper way

**Comment by jtavva** [comment] 2021-02-03 22:01
@sudaristvan 

Thank you so much for reaching out to us. It is hard to debug your problem with just two lines of code.

Please verify your  getNextWord() matches with the code block in step 8
![image](https://user-images.githubusercontent.com/24260141/106814557-6fc6f680-6627-11eb-811f-2b8555763f62.png)

If the problem still persists....
Please verify your final code matches with the code at the end of the codelab. 
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#12

If that also does't solve the problem please zip and share your code

**Comment by jtavva** [comment] 2021-03-01 21:38
@sudaristvan 
It's been more than 3 weeks since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.

**Closed by jtavva** 2021-03-01 21:38 UTC
Labels: question

**Comment by ratneshnavlakhe** [comment] 2021-07-29 12:54
Hi @jtavva the issue is with 
`private var wordsList: MutableList<String> = mutableListOf()`

While launching the app it tries to call getNextWord() method, and in if statement it checks for 
 `if (wordsList.contains(currentWord)) {`

There it is crashing with the message

`java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
        at com.example.android.unscramble.ui.game.GameViewModel.getNextWord(GameViewModel.kt:42)
        at com.example.android.unscramble.ui.game.GameViewModel.<init>(GameViewModel.kt:10)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.android.unscramble.ui.game.GameFragment.getViewModel(Unknown Source:2)
        at com.example.android.unscramble.ui.game.GameFragment.updateNextWordOnScreen(GameFragment.kt:135)
        at com.example.android.unscramble.ui.game.GameFragment.onViewCreated(GameFragment.kt:62)`

Not sure why it is not able to call the method .contains on mutableList() ?

**Comment by pinventado** [comment] 2021-08-05 19:50
I have the same issue. The way I got it to work was make `wordsList` a `lateinit` variable, then initialize it in the `init` block. Something like this:

```Kotlin
    private lateinit var wordsList: MutableList<String>
    init {
        Log.d("GameFragment", "GameViewModel created!")
        wordsList = mutableListOf()
        getNextWord()
    }
```

**Comment by pinventado** [comment] 2021-08-05 21:44
I think I figured it out. The `wordsList` variable had to be declared above the `init` block for it to work. I guess that means the placement of a property initialization relative to the `init` block that uses it matters.

```Kotlin
private var wordsList: MutableList<String> = mutableListOf()
init {
        Log.d("GameFragment", "GameViewModel created!")
        getNextWord()
    }
```

**Comment by theyashgrover** [comment] 2021-08-08 15:38
Hello , I am getting an issue with my application.. I am unable to figure it out but my app just isn't opening , It's crashing and my mobile is showing the following error (Unscramble failed to restart several times .  Restore It by clearing history..) , Also , I made sure that my code matches the code mentioned in the solution code of the codelab :- [(https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#11)]

Please help me as soon as possible.. #

**Comment by pinventado** [comment] 2021-08-08 15:40
There's usually an exception that causes your app to close. Try looking at the terminal output or run it in debug mode to find out what is causing the problem.
